sudo: required
services:
  - docker

before_install:
  - docker build -t abilgaiyan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abilgaiyan/docker-react npm run test -- --coverage
